
publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under uploads/versions

backend:
  name: git-gateway
  # repo: https://github.com/sites-yari/pnch_ementa
  repo: https://github.com/sites-yari/alchemist_site
  branch: master # Branch to update (optional; defaults to master)


collections: #====================| POSTS |===================================================|  
  - name: "data" #|=====================| DATA |====================================================|
    label: "Data"
    editor:
      preview: true
    files: 
      # ---| HEADER |---
      - name: "header"
        label: "Header"
        file: "_data/header.yml"
        description: Everything needed from the Navbar
        fields:
          - { label: "Titulo", name: "title", widget: "string" }
          - { label: "Link do titulo", name: "link_title", widget: "string" }
          - { label: "Logo", name: "img", widget: "string" }
          - label: "Left side"
            name: left
            widget: "object"
            fields:
              - label: "Button 1"
                name: btn1
                widget: "object"
                fields:
                  - { label: "Texto", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Button 2"
                name: btn2
                widget: "object"
                fields:
                  - { label: "Texto", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Button 3"
                name: btn3
                widget: "object"
                fields:
                  - { label: "Texto", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
      # ---| FOOTER |---
      - name: "footer"
        label: "Footer"
        file: "_data/footer.yml"
        description: Everything needed from the footer
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Link do twitter", name: "twitter_link", widget: "string" }
          - { label: "link do Linkedin", name: "linkedin_link", widget: "string" }
          - { label: "link do Instagram ", name: "insta_link", widget: "string" }
      # ---| INDEX |---
      - name: "homepage"
        label: "Homepage"
        file: "_data/homepage.yml"
        description: Everything needed for the index
        fields:
          - label: "Conteudo 1"
            name: content1
            widget: "object"
            fields:
              - { label: "Titulo parte 1", name: "title_part1", widget: "string" }
              - { label: "Titulo parte 2", name: "title_part2", widget: "string" }
              - { label: "Entre os Titulos 1 e 2", name: "gold_title", widget: "string" }
              - { label: "Descrição", name: "desc", widget: "string" }
              - { label: "Imagem", name: "img", widget: "string" }
          - label: "Conteudo 2"
            name: content2
            widget: "object"
            fields:
              - label: "Goal 1"
                name: goal1
                widget: "object"
                fields:
                  - { label: "Titulo", name: "title", widget: "string" }
                  - { label: "Descrição", name: "desc", widget: "string" }
                  - { label: "Imagem", name: "img", widget: "string" }
              - label: "Goal 2"
                name: goal2
                widget: "object"
                fields:
                  - { label: "Titulo", name: "title", widget: "string" }
                  - { label: "Descrição", name: "desc", widget: "string" }
                  - { label: "Imagem", name: "img", widget: "string" }
          - label: "Conteudo 3"
            name: content3
            widget: "object"
            fields:
              - { label: "Titulo", name: "title", widget: "string" }
              - { label: "Descrição", name: "desc", widget: "string" }
              - label: "Caixa 1"
                name: box1
                widget: "object"
                fields:
                  - { label: "Titulo", name: "title", widget: "string" }
                  - { label: "Descrição", name: "desc", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
              - label: "Caixa 2"
                name: box2
                widget: "object"
                fields:
                  - { label: "Titulo", name: "title", widget: "string" }
                  - { label: "Descrição", name: "desc", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
          - label: "Conteudo 4"
            name: content4
            widget: "object"
            fields:
              - { label: "Titulo", name: "title", widget: "string" }
              - { label: "Logo", name: "img_logo", widget: "string" }
              - { label: "IOS link", name: "ios_link", widget: "string" }
              - { label: "Android link", name: "android_link", widget: "string" }
              - label: "Caixa 1"
                name: box1
                widget: "object"
                fields:
                  - { label: "Texto 1", name: "opt1", widget: "string" }
                  - { label: "Texto 2", name: "opt2", widget: "string" }
                  - { label: "Texto 3", name: "opt3", widget: "string" }
              