
publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under uploads/versions

backend:
  name: git-gateway
  # repo: https://github.com/sites-yari/pnch_ementa
  repo: https://github.com/sites-yari/alchemist_site
  branch: master # Branch to update (optional; defaults to master)


collections: #====================| POSTS |===================================================|  
  - name: "data" #|=====================| DATA |====================================================|
    label: "Data"
    editor:
    preview: true
    files:
      - name: "downloads"
        label: "Downloads"
        file: "_data/downloads.yml"
        description: Downloads section
        fields:
          - label: "Section downloads app store"
            name: downloads_app_store
            widget: "object"
            fields:
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
          - label: "Section downloads google play"
            name: downloads_google_play
            widget: "object"
            fields:
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
      # ---| HEADER |---
      - name: "header"
        label: "Header"
        file: "_data/header.yml"
        description: Everything needed from the Navbar
        fields:
          - { label: "Titulo", name: "title", widget: "string" }
          - { label: "Link do titulo", name: "link_title", widget: "string" }
          - { label: "Logo", name: "img", widget: "string" }
          - label: "Left side"
            name: left
            widget: "object"
            fields:
              - label: "Button 1"
                name: btn1
                widget: "object"
                fields:
                  - { label: "Texto", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Button 2"
                name: btn2
                widget: "object"
                fields:
                  - { label: "Texto", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Button 3"
                name: btn3
                widget: "object"
                fields:
                  - { label: "Texto", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
      # ---| FOOTER |---
      - name: "footer"
        label: "Footer"
        file: "_data/footer.yml"
        description: Everything needed from the footer
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Link do twitter", name: "twitter_link", widget: "string" }
          - { label: "link do Linkedin", name: "linkedin_link", widget: "string" }
          - { label: "link do Instagram ", name: "insta_link", widget: "string" }

      # ---| INDEX |---
      - name: "homepage"
        label: "Homepage"
        file: "_data/homepage.yml"
        description: Everything needed for the index
        fields:
          - label: "Section 1"
            name: content_1
            widget: "object"
            fields:
              - { label: "Title part 1", name: "title_part1", widget: "string" }
              - { label: "Title part 2", name: "title_part2", widget: "string" }
              - { label: "Between title 1 e 2", name: "gold_title", widget: "string" }
              - { label: "Description", name: "desc", widget: "string" }
              - { label: "Image", name: "img", widget: "string" }

          - label: "Template sections"
            name: "section_template"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - label: "Template section"
                name: template_section
                widget: "object"
                fields:
                  - label: "Template section type"
                    name: "section_type"
                    widget: "select"
                    default: "section-1"
                    options:
                      - { label: "promotional", value: "promotional" }
                      - { label: "Section type 1 - featured image right", value: "section-1" }
                      - { label: "Section type 2 - featured image center", value: "section-2" }
                      - { label: "Section type 3 - featured image left", value: "section-3" }
                      - { label: "Section simple background color", value: "bg-color" }
                      - { label: "Section title-highlighted", value: "bg-color-title-highlighted" }
                      # - { label: "Section full video 1", value: "section-video-1" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Title", name: "title_2", widget: "string" }
                  - { label: "Description", name: "desc", widget: "markdown" }
                  - { label: "Featured Image", name: "img", widget: "string" }
                  - { label: "Image bg for replacement of default (applied to selected type)", name: "bg_data", widget: "string" }
                  - { label: "Color bg for replacement of default (applied to selected type)", name: "bg_data_color", widget: "string" }
                  - { label: "Include relative nested html file", name: "include_relative", widget: "string", default: '' }

          - label: "Section 2"
            name: section_2
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Description", name: "desc", widget: "markdown" }
          - label: "Section 3"
            name: section_3
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Image bg for replacement of default", name: "bg_data", widget: "string" }
              - { label: "Description", name: "desc", widget: "markdown" }
          - label: "Section 4"
            name: section_4
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Description", name: "desc", widget: "markdown" }
          - label: "Section 5"
            name: section_5
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Title <highlighted> ", name: "title_2", widget: "string" }
              - { label: "Color bg for replacement of default", name: "bg_data_color", widget: "string" }
              - { label: "Description", name: "desc", widget: "markdown" }

          - label: "Section 6"
            name: section_6
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "markdown" }
              - { label: "Featured Image", name: "img", widget: "string", default: "../assets/imgs/bg-wire-2.png"}
              - { label: "YouTube embed token", name: "youtube_embed_token", widget: "string", default: "0mHmrNdaiBY" }

          - label: "Section 7"
            name: section_7
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Description", name: "desc", widget: "markdown" }

          - label: "Stepper"
            name: "stepper"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Show step numbers", name: "showStepNumbers", widget: "boolean", default: false }
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - label: "Step"
                    name: "step"
                    widget: "object"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Image Mask URL", name: "imgMask", widget: "string" }
                      - { label: "Image Show mask", name: "usingImgMask", widget: "select", default: "active",  options: ["disabled", "active"] }
                      - { label: "Media type", name: "mediaType", widget: "select", default: "image",  options: ["image", "video"] }
                      - { label: "Image URL", name: "img", widget: "string" }
                      - { label: "Image show in mobile", name: "showImgMobile", widget: "boolean", default: true }
                      - { label: 'Description of step', name: 'description', widget: 'markdown' }
